version: "3.8"

services:
  backend:
    build: ./badminton-stats-tracker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./badminton-stats-tracker-backend/.env
    restart: unless-stopped

  frontend:
    build: ./badminton-stats-tracker-frontend
    ports:
      - "3000:80"  # Serve frontend at http://your-ec2-ip:3000
    env_file:
      - ./badminton-stats-tracker-frontend/.env
    depends_on:
      - backend
    restart: unless-stopped